{
 "title": "Sockshop Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(order_new_seconds_count, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Instructions",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Sockshop Dashboard for namespace: $Namespace\n\n\n\nPlease select the namespace above to view details for for that namespace.\n\n\n"
  },
  {
   "title": "Total Orders",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(order_new_seconds_count{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Orders Received per Minute",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(order_new_seconds_count{namespace=~\"$Namespace\"}[1m])*60)"
    }
   ]
  },
  {
   "title": "Avg Order Processing Time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(order_new_seconds_sum{namespace=~\"$Namespace\"} / order_new_seconds_count{namespace=~\"$Namespace\"})  "
    }
   ]
  },
  {
   "title": "Successful Payments",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "payment_success_total{namespace=~\"$Namespace\"}"
    }
   ]
  },
  {
   "title": "Failed Payments",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "payment_failure_total{namespace=~\"$Namespace\"}"
    }
   ]
  },
  {
   "title": "Payment Success Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "payment_success_total{namespace=~\"$Namespace\"} / (payment_success_total{namespace=~\"$Namespace\"} + payment_failure_total{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Orders Processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Orders" }
   ],
   "targets": [
    {
     "expr": "order_new_seconds_count{namespace=~\"$Namespace\"} - (order_new_seconds_count{namespace=~\"$Namespace\"} offset $__interval)",
     "legendFormat": "Orders"
    }
   ]
  },
  {
   "title": "Payments Processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "payment_success_total{namespace=~\"$Namespace\"} - (payment_success_total{namespace=~\"$Namespace\"} offset $__interval)",
     "legendFormat": "Payment Successes"
    },
    {
     "expr": "payment_failure_total{namespace=~\"$Namespace\"} - (payment_failure_total{namespace=~\"$Namespace\"} offset $__interval)",
     "legendFormat": "Payment Failures"
    }
   ]
  },
  {
   "title": "Overall Order Processing Time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "min_over_time((order_new_seconds_sum{namespace=~\"$Namespace\"} / order_new_seconds_count{namespace=~\"$Namespace\"})[1d:])",
     "legendFormat": "Minimum"
    },
    {
     "expr": "avg_over_time((order_new_seconds_sum{namespace=~\"$Namespace\"} / order_new_seconds_count{namespace=~\"$Namespace\"})[1d:])",
     "legendFormat": "Mean"
    },
    {
     "expr": "max_over_time((order_new_seconds_sum{namespace=~\"$Namespace\"} / order_new_seconds_count{namespace=~\"$Namespace\"})[1d:])",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "REST Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(payments_authorize_total{namespace=~\"$Namespace\"} - (payments_authorize_total{namespace=~\"$Namespace\"} offset $__interval)) + sum(ship_seconds_count{namespace=~\"$Namespace\"} - (ship_seconds_count{namespace=~\"$Namespace\"} offset $__interval)) > 0",
     "legendFormat": "Role: {{role}}"
    }
   ]
  }
 ]
}