#
# Copyright (c) 2021, 2022 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
server:
  port: ${port:8082}
spring:
  application:
    name: Payment
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
logging:
  level:
    root: warn
    "Coherence": info
    org.springframework.web: info
    com.oracle.coherence.spring: info
    org.apache.http: debug
otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://jaeger-inmemory-instance-collector:4318/v1/traces
