= Users Service

The *Users Service* covers user account storage, provide user login, register and
retrieval for:

- users
- cards
- addresses

It contains service implementation, including
link:./src/main/java/io/micronaut/examples/sockshop/users/User.java[domain model],
link:./src/main/java/io/micronaut/examples/sockshop/users/UserResource.java[REST API],
as well as the link:./src/main/java/io/micronaut/examples/sockshop/users/UserRepository.java[data repository abstraction]
and its https://coherence.java.net/[Coherence] link:src/main/java/io/micronaut/examples/sockshop/users/CoherenceUserRepository.java[implementation].

== API

The service exposes REST API on port 8080.

TBD (add OpenAPI support/link)

== Building the service

In order to build project and create Docker images for the service, simply run the
following commands:

[source,bash]
----
$ mvn clean install
$ mvn package -Pdocker -DskipTests
----

The first command will build project, run unit and integration tests, and install the
artifacts that need to be included into the Docker images into the local Maven repo.

The second command will then package those artifacts, and all of their dependencies, into
the local Docker image.

You can then manually push generated image to a Docker repository of your choice in order
to make it available to other environments.

Alternatively, you can build and push the image directly to a remote Docker repository by
running the following command instead:

[source,bash]
----
$ mvn package -Pdocker -DskipTests -Ddocker.repo=<your_docker_repo> -Djib.goal=build
----

You should replace `<your_docker_repo>` in the command above with the name of the
Docker repository that you can push images to.

== Running the service

Coherence is embedded into your application and runs as part
of your application container so it allows you to easily scale your service to hundreds of *stateful*,
and optionally *persistent* nodes.

To run Coherence implementation of the service, simply execute

[source,bash]
----
$ docker run -p 8080:8080 ghcr.io/coherence-sockshop-micronaut/users
----

As a basic test, you should be able to perform an HTTP GET against `/customers` endpoint:

[source,bash]
----
$ curl http://localhost:8080/customers
----

which should return 200 response code and a list of customers.

To learn how to run the service in Kubernetes, as part of a larger Sock Shop application,
please refer to the xref:../sockshop/README.adoc[main documentation page].

== License

The Universal Permissive License (UPL), Version 1.0
